version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: asia-east1-docker.pkg.dev/animated-spider-404200/ai-project/llm-backend:latest
    ports:
      - 8000:8000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: asia-east1-docker.pkg.dev/animated-spider-404200/ai-project/llm-frontend:latest
    ports:
      - 8501:8501
    depends_on:
      - backend
